#!/usr/bin/env python3
"""
Script para gerar imagens dos game cards usando Nano Banana
"""

import requests
import json
import sys
import time
from pathlib import Path

# Prompts para cada jogo
GAME_PROMPTS = {
    'jogo-da-velha': 'Minimalist illustration of a tic-tac-toe grid with X and O symbols, clean geometric style, green and yellow colors, football theme, modern design, vector art',
    'wordle': 'Minimalist illustration of colorful letter tiles in a grid, word game aesthetic, green yellow red colors, clean typography, modern flat design, vector art',
    'quem-e-o-craque': 'Professional football player with gradient blur effect, detective theme with magnifying glass, modern minimalist illustration, vector art',
    'conexoes': 'Four connected nodes with lines, network visualization, purple colors, abstract geometric pattern, modern tech aesthetic, vector art',
    'carreira': 'Career progression timeline with ascending path, football player journey, green gradient, modern minimalist, vector art',
    'duelo': 'Two football players facing each other VS duel, action pose, red and green colors, dynamic, vector illustration',
    'linha-do-tempo': 'Timeline with football moments, chronological markers, blue colors, elegant minimalist, vector art',
    'escudo': 'Fragmented shield puzzle pieces, team emblem concept, blue colors, modern illustration, vector art',
    'camisa': 'Football jersey number 10, classic design, yellow colors, iconic sports imagery, minimalist, vector art',
}

def generate_with_nano_banana(prompt: str, api_key: str) -> str:
    """Generate image using Nano Banana API"""

    url = "https://api.nanobananai.com/v1/images/generate"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    data = {
        "prompt": prompt,
        "model": "flux-1-dev",
        "width": 512,
        "height": 400,
        "steps": 20,
        "guidance_scale": 7.5,
    }

    print(f"    Calling Nano Banana API...")
    response = requests.post(url, headers=headers, json=data, timeout=60)

    if response.status_code == 200:
        result = response.json()
        if 'images' in result and len(result['images']) > 0:
            return result['images'][0]
        else:
            raise Exception(f"No images in response: {result}")
    else:
        raise Exception(f"API Error: {response.status_code} - {response.text}")

def main():
    api_key = None

    # Check for API key
    if 'NANO_BANANA_API_KEY' in sys.environ:
        api_key = sys.environ['NANO_BANANA_API_KEY']
    else:
        print("ERROR: Set NANO_BANANA_API_KEY environment variable")
        print("\nUsage:")
        print("  set NANO_BANANA_API_KEY=your_key_here")
        print("  python scripts/generate-images.py")
        sys.exit(1)

    images_file = Path(__file__).parent.parent / 'lib' / 'generated-images.ts'

    print(f"Generating images with Nano Banana...")
    print(f"API Key: {api_key[:10]}...")

    image_urls = {}

    for game, prompt in GAME_PROMPTS.items():
        try:
            print(f"\n  [{game}] {prompt[:50]}...")
            url = generate_with_nano_banana(prompt, api_key)
            image_urls[game] = url
            print(f"    ✓ Success!")
            time.sleep(1)  # Rate limiting
        except Exception as e:
            print(f"    ✗ Error: {e}")
            image_urls[game] = None  # Fallback

    # Write to TypeScript file
    ts_content = f"""// Auto-generated by scripts/generate-images.py
// Generated images for game cards
export const GAME_IMAGES: Record<string, string> = {json.dumps(image_urls, indent=2)};

export function getGameImage(gameType: string): string {{
  return GAME_IMAGES[gameType as keyof typeof GAME_IMAGES] ||
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&h=400&fit=crop&q=80'
}}
"""

    images_file.write_text(ts_content)
    print(f"\n✓ Generated images saved to {images_file}")
    print(f"\nGenerated {sum(1 for v in image_urls.values() if v)} images successfully")

if __name__ == '__main__':
    main()
